Emotion6_classes = [
    "anger",
    "disgust",
    "fear",
    "joy",
    "sadness",
    "surprise"
]

ds_specific_templates = {
    # Comprehensive Emotion6 Templates - 100+ diverse templates covering all visual representations
    'Emotion6': [
    # Basic emotional representation templates
    'a photo representing {}.',
    'an image that evokes {}.',
    'a picture that conveys {}.',
    'a visual representation of {}.',
    'a scene depicting {}.',
    'an image associated with {}.',
    'a photograph that expresses {}.',
    'a picture that symbolizes {}.',
    'content that represents the emotion of {}.',
    'a visual that embodies {}.',
    
    # Human expression and portrait templates
    'a photo of a {} face.',
    'a photo of a person showing {}.',
    'a photo of a {} expression.',
    'a picture of someone feeling {}.',
    'a facial expression of {}.',
    'a person expressing {}.',
    'a {} facial expression.',
    'someone displaying {}.',
    'a face showing {}.',
    'a portrait of {} emotion.',
    'a child expressing {}.',
    'an adult showing {}.',
    'people experiencing {}.',
    'a human moment of {}.',
    'eyes that reflect {}.',
    
    # Nature and landscape templates
    'a landscape that evokes {}.',
    'nature representing {}.',
    'a natural scene of {}.',
    'weather that suggests {}.',
    'a sky that conveys {}.',
    'clouds that express {}.',
    'a sunset that embodies {}.',
    'water that reflects {}.',
    'mountains that inspire {}.',
    'a forest scene of {}.',
    'natural elements suggesting {}.',
    'outdoor scenery evoking {}.',
    'a beach scene representing {}.',
    'wilderness that conveys {}.',
    'seasonal imagery of {}.',
    
    # Animal and creature templates
    'an animal showing {}.',
    'a creature expressing {}.',
    'wildlife that represents {}.',
    'a pet displaying {}.',
    'an animal in a {} state.',
    'birds that symbolize {}.',
    'marine life suggesting {}.',
    'domestic animals expressing {}.',
    'wild animals embodying {}.',
    'creatures in {} situations.',
    
    # Object and symbolic templates
    'an object that represents {}.',
    'something that symbolizes {}.',
    'an item associated with {}.',
    'a thing that causes {}.',
    'something that triggers {}.',
    'an element that conveys {}.',
    'a symbol of {}.',
    'something representing the feeling of {}.',
    'an object that evokes {}.',
    'something that embodies {}.',
    'colors that suggest {}.',
    'textures that evoke {}.',
    'patterns representing {}.',
    'shapes that convey {}.',
    'materials that express {}.',
    
    # Architecture and environment templates
    'buildings that evoke {}.',
    'architecture representing {}.',
    'urban scenes of {}.',
    'interior spaces suggesting {}.',
    'rooms that convey {}.',
    'structures that embody {}.',
    'cityscapes of {}.',
    'abandoned places representing {}.',
    'modern spaces evoking {}.',
    'historical settings of {}.',
    'public spaces that suggest {}.',
    'private spaces expressing {}.',
    
    # Food and consumables templates
    'food that represents {}.',
    'a meal suggesting {}.',
    'cuisine that evokes {}.',
    'drinks that symbolize {}.',
    'cooking that expresses {}.',
    'ingredients representing {}.',
    'dining scenes of {}.',
    'culinary moments of {}.',
    
    # Artistic and creative templates
    'art that expresses {}.',
    'a painting of {}.',
    'sculpture representing {}.',
    'creative work showing {}.',
    'artistic expression of {}.',
    'crafts that embody {}.',
    'design elements suggesting {}.',
    'visual art conveying {}.',
    'handmade items of {}.',
    'artistic interpretation of {}.',
    
    # Activity and action templates
    'activities that bring {}.',
    'actions that cause {}.',
    'movement expressing {}.',
    'sports that evoke {}.',
    'games representing {}.',
    'work that suggests {}.',
    'recreation that embodies {}.',
    'hobbies that convey {}.',
    'exercise expressing {}.',
    'play that represents {}.',
    
    # Abstract and conceptual templates
    'the concept of {}.',
    'the essence of {}.',
    'the embodiment of {}.',
    'the manifestation of {}.',
    'the representation of {}.',
    'the visualization of {}.',
    'the expression of {}.',
    'the display of {}.',
    'the demonstration of {}.',
    'the illustration of {}.',
    'abstract imagery of {}.',
    'conceptual art representing {}.',
    'symbolic representation of {}.',
    'metaphorical imagery of {}.',
    'allegorical scenes of {}.',
    
    # Contextual and atmospheric templates
    'an atmosphere of {}.',
    'a mood of {}.',
    'an ambiance suggesting {}.',
    'lighting that evokes {}.',
    'shadows that represent {}.',
    'brightness that conveys {}.',
    'darkness expressing {}.',
    'contrasts that embody {}.',
    'tones that suggest {}.',
    'hues representing {}.',
    
    # Temporal and situational templates
    'a moment of {}.',
    'an instant of {}.',
    'a memory of {}.',
    'a dream about {}.',
    'a nightmare of {}.',
    'anticipation of {}.',
    'preparation for {}.',
    'aftermath of {}.',
    'during times of {}.',
    'in seasons of {}.',
    
    # Sensory and experiential templates
    'something that feels {}.',
    'textures that seem {}.',
    'sounds that suggest {}.',
    'silence that represents {}.',
    'chaos that embodies {}.',
    'order that expresses {}.',
    'confusion representing {}.',
    'clarity that conveys {}.',
    'complexity suggesting {}.',
    'simplicity embodying {}.'
    ],
        # Comprehensive Abstract Art Templates - 120+ diverse templates covering all visual and emotional aspects
    'Abstract': [
    # Basic abstract art representation templates
    'an abstract artwork that evokes {}.',
    'an abstract painting representing {}.',
    'an abstract image that conveys {}.',
    'abstract art that embodies {}.',
    'a non-representational artwork expressing {}.',
    'an abstract composition that suggests {}.',
    'abstract visual elements that evoke {}.',
    'a painting that abstractly represents {}.',
    'abstract imagery that embodies the feeling of {}.',
    'non-figurative art that expresses {}.',
    
    # Color and composition templates specific to abstract art
    'abstract colors that evoke {}.',
    'color combinations in abstract art representing {}.',
    'abstract color fields expressing {}.',
    'chromatic abstractions that convey {}.',
    'color relationships that suggest {}.',
    'abstract color harmony embodying {}.',
    'pigments arranged to express {}.',
    'abstract color contrasts evoking {}.',
    'hues and tones that represent {}.',
    'abstract color interactions suggesting {}.',
    
    # Form and shape templates for abstract art
    'abstract forms that convey {}.',
    'geometric shapes expressing {}.',
    'organic forms in abstract art representing {}.',
    'abstract shapes that embody {}.',
    'non-representational forms evoking {}.',
    'abstract geometries that suggest {}.',
    'flowing forms that express {}.',
    'angular abstractions conveying {}.',
    'curvilinear elements representing {}.',
    'abstract structural forms embodying {}.',
    
    # Texture and surface quality templates
    'abstract textures that evoke {}.',
    'surface qualities in abstract art expressing {}.',
    'textural elements that convey {}.',
    'abstract surface treatments representing {}.',
    'tactile qualities in abstraction suggesting {}.',
    'material textures that embody {}.',
    'abstract surface variations evoking {}.',
    'layered textures expressing {}.',
    'smooth abstractions that convey {}.',
    'rough textural abstractions representing {}.',
    
    # Movement and rhythm templates
    'abstract movement expressing {}.',
    'rhythmic patterns in abstract art evoking {}.',
    'dynamic abstractions that convey {}.',
    'flowing movements in abstract art representing {}.',
    'static compositions that embody {}.',
    'energetic abstract elements suggesting {}.',
    'calm abstract rhythms expressing {}.',
    'turbulent abstract movement evoking {}.',
    'gentle abstract flows that convey {}.',
    'aggressive abstract dynamics representing {}.',
    
    # Scale and proportion templates
    'large-scale abstractions that evoke {}.',
    'intimate abstract works expressing {}.',
    'monumental abstract art conveying {}.',
    'small abstract details representing {}.',
    'expansive abstract compositions embodying {}.',
    'compressed abstract elements suggesting {}.',
    'overwhelming abstract scale evoking {}.',
    'delicate abstract proportions expressing {}.',
    'bold abstract dimensions that convey {}.',
    'subtle abstract relationships representing {}.',
    
    # Light and shadow in abstraction
    'abstract light effects expressing {}.',
    'shadows in abstract art evoking {}.',
    'luminous abstractions that convey {}.',
    'dark abstract elements representing {}.',
    'bright abstract passages embodying {}.',
    'contrast between light and dark suggesting {}.',
    'glowing abstract forms evoking {}.',
    'shadowy abstractions expressing {}.',
    'radiant abstract compositions that convey {}.',
    'subdued abstract lighting representing {}.',
    
    # Spatial relationships in abstract art
    'abstract spatial relationships expressing {}.',
    'depth in abstract art evoking {}.',
    'flat abstract compositions that convey {}.',
    'layered abstract spaces representing {}.',
    'compressed abstract depth embodying {}.',
    'expansive abstract space suggesting {}.',
    'crowded abstract elements evoking {}.',
    'sparse abstract arrangements expressing {}.',
    'dense abstract compositions that convey {}.',
    'open abstract fields representing {}.',
    
    # Medium and technique specific templates
    'oil painting abstractions that evoke {}.',
    'watercolor abstractions expressing {}.',
    'acrylic abstract works conveying {}.',
    'mixed media abstractions representing {}.',
    'digital abstract art embodying {}.',
    'collage elements in abstraction suggesting {}.',
    'painted abstract surfaces evoking {}.',
    'drawn abstract elements expressing {}.',
    'printmaking abstractions that convey {}.',
    'sculptural abstractions representing {}.',
    
    # Artistic style and movement templates
    'expressionist abstractions that evoke {}.',
    'minimalist abstract art expressing {}.',
    'gestural abstractions conveying {}.',
    'geometric abstractions representing {}.',
    'lyrical abstract works embodying {}.',
    'hard-edge abstractions suggesting {}.',
    'action painting elements evoking {}.',
    'color field paintings expressing {}.',
    'contemporary abstractions that convey {}.',
    'modern abstract works representing {}.',
    
    # Emotional intensity and complexity templates
    'subtle abstract expressions of {}.',
    'intense abstract manifestations of {}.',
    'complex abstract emotions including {}.',
    'simple abstract representations of {}.',
    'overwhelming abstract expressions of {}.',
    'gentle abstract suggestions of {}.',
    'powerful abstract statements of {}.',
    'delicate abstract hints of {}.',
    'bold abstract declarations of {}.',
    'nuanced abstract expressions of {}.',
    
    # Conceptual and philosophical templates
    'abstract concepts visualizing {}.',
    'non-verbal abstract communication of {}.',
    'pure abstract emotion of {}.',
    'distilled abstract essence of {}.',
    'concentrated abstract feeling of {}.',
    'abstract meditation on {}.',
    'visual abstract poetry of {}.',
    'abstract philosophical expression of {}.',
    'transcendent abstract representation of {}.',
    'universal abstract language of {}.',
    
    # Viewer response and interpretation templates
    'abstractions that make viewers feel {}.',
    'abstract art that inspires {}.',
    'visual abstractions that trigger {}.',
    'abstract works that generate {}.',
    'paintings that abstractly communicate {}.',
    'art that non-representationally expresses {}.',
    'abstractions that universally convey {}.',
    'visual languages of abstract {}.',
    'non-literal artistic expressions of {}.',
    'abstract artistic interpretations of {}.'
    ]
}